VLSMVersion_3/Controllers/VLSM_Controller.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Contracts;
using DatabaseContext;
using Microsoft.EntityFrameworkCore;
using VLSMVersion_3.Models;

namespace VLSMVersion_3.Controllers
{
    public class VLSM_Controller : Controller
    {
        public List<Lans> _LansList { get; set; }
        // GET: VLSM_Controller/Create
        public ActionResult Create()
        {
            return View();
        }

        private VlsmDb _context;
        private IRepositoryManager _repositoryManager;

        public VLSM_Controller(IRepositoryManager repositoryManager, VlsmDb context)
        {
            _repositoryManager = repositoryManager;
            _context = context;
        }

        // POST: VLSM_Controller/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(VLSM_Model model)
        {

            if (ModelState.IsValid)
            {

                ViewData["IP_Address"] = model.IP_Address;

                ViewData["LansValues"] = model.LansValues;
                _LansList = model.LansValues;
                ViewData["cidrValue"] = model.cidrValue;
                ViewData["NetworkID"] = model.NetworkID();
                ViewData["TotalHosts"] = model.AvailableHosts(); 
                ViewData["FinalResult"] = model.GetSubAndMask();
            }


            return View("VlsmResultNew");
        }

        [HttpGet]
        public IActionResult DisplayDatabase()
        {
            return View(_repositoryManager.Vlsm.GetAllResults(trackChanges: false));
        }
        

        // POST: VLSM_Controller/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(DisplayDatabase));
            }
            catch
            {
                return View("Create");
            }
        }

        
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vlsmresult = await _context.Vlsmresults
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vlsmresult == null)
            {
                return NotFound();
            }

            return View(vlsmresult);
        }

        // POST: Vlsmresults/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var vlsmresult = await _context.Vlsmresults.FindAsync(id);
            _context.Vlsmresults.Remove(vlsmresult);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(DisplayDatabase));
        }

        private bool VlsmresultExists(long id)
        {
            return _context.Vlsmresults.Any(e => e.Id == id);
        }
        
    }
}

VLSMVersion_3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VLSMVersion_3</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="background-color: #9fcdff">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VLSMVersion_3</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="btn btn-info" style="margin-right: 5px" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-info" style="margin-right: 5px" asp-area="" asp-controller="Home" asp-action="Author">Author</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-info" style="margin-right: 5px" asp-area="" asp-controller="VLSM_" asp-action="Create">VLSM CALCULATE</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-info" style="margin-right: 5px" asp-area="" asp-controller="VLSM_" asp-action="DisplayDatabase">DISPLAY DATABASE CONTENT</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - VLSMVersion_3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>